# Generated by Django 3.1 on 2020-08-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='date',
        ),
    ]
