# Generated by Django 3.1 on 2020-08-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200825_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='article_pic'),
        ),
    ]
